### ISSUE TITLE
cosmic-base/cosmic-settings: missing dependency libpulse

### ISSUE THREAD

**Issue by HyperWinX** [aladmit/cosmic-overlay#1]
Hi there! We noticed issue in ebuild of cosmic-settings. One of Gentoo users tried to emerge COSMIC DE, and build failed because of missing libpulse dependency. Here is full build log: [XEk0.log](https://github.com/user-attachments/files/17298154/XEk0.log)
Line that says about libpulse: 
`[0m  [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: /usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -l:libpulse.so.0: No such file or directory[0m`

Thats my first ever bug report, sorry if i did something wrong.

**Comment by aladmit** [comment]
Thanks! I added `media-libs/libpulse` as build dependency 👍🏼
